version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - ":3306" # Mapea puerto 3306 del contenedor a puerto 3306 del host
    environment:
      MYSQL_ROOT_PASSWORD: 'P@ssword123'
      MYSQL_DATABASE: 'dcrm_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'P@ssword123'

    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic --noinput && service apache2 start && apache2ctl configtest && python manage.py runserver"
    ports:
      #- "8000:8000" # Mapea puerto 8000 del contenedor a puerto 8000 del host
      - "8080:80" # Mapea puerto 80 del contenedor a puerto 80 del host
    volumes:
      - .:/app
      - ./dcrm_site.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db

volumes:
  mysql_data: